#ifndef __TASKS_STACK_AND_PRIO_H
#define __TASKS_STACK_AND_PRIO_H

/*
 * Priority
 */
#define MIN_TASK_PRIORITY tskIDLE_PRIORITY + 0
//
#define TASK_PRIORITY_01  MIN_TASK_PRIORITY + 1
//
#define TASK_PRIORITY_02  TASK_PRIORITY_01 + 1
//
#define TASK_PRIORITY_03  TASK_PRIORITY_02 + 1
//
#define TASK_PRIORITY_04  TASK_PRIORITY_03 + 1
//
#define TASK_PRIORITY_05  TASK_PRIORITY_04 + 1
//
#define TASK_PRIORITY_06  TASK_PRIORITY_05 + 1
//
#define TASK_PRIORITY_07  TASK_PRIORITY_06 + 1
//
#define TASK_PRIORITY_08  TASK_PRIORITY_07 + 1
//
#define MAX_TASK_PRIORITY TASK_PRIORITY_08 + 1

/*
 * Stack size
 */
#define HEALTH_CHECK_TASK_STACK 2 * configMINIMAL_STACK_SIZE

#endif /* __TASKS_STACK_AND_PRIO_H */

